# list of character names that are inconsistent or have typos, and what they should be converted to
char_replacement_ls = [
    ('TSUTEY',"TSU'TEY"),
    ('PEPPER POTTS','PEPPER'),
    ('TONY','IRON MAN'),
    ('STARK','IRON MAN'),
    ('STEVE','CAPTAIN AMERICA'),
    ('TONY','STARK'),
    ('AGENT PHIL COULSON','COULSON'),
    ('NATASHA','BLACK WIDOW'),
    ('BANNER','HULK'),
    ('THE BEAST','BEAST'),
    ("YOUNG T'CHAKA","T'CHAKA"),
    ("YOUNGT'CHAKA","T'CHAKA"),
    ("N' JOBU","N'JOBU"),
    ("T' CHALLA","T'CHALLA"),
    ("KILLMON GER","KILLMONGER"),
    ("W' KABI","W'KABI"),
    ("YOUNGKILLMONGER","KILLMONGER"),
    ("M' BAKU","M'BAKU"),
    ("T' CHAKA","T'CHAKA"),
    ('MR. TUMNUS','TUMNUS'),
    ("YOUNG DE LA CRUZ", "DE LA CRUZ"),
    ("YOUNG HÉCTOR", "HÉCTOR"),
    ("WAYNE", "BATMAN"),
    ("YOUNG ANNA", "ANNA"),
    ("YOUNG ELSA", "ELSA"),
    ("YOUNG KRISTOFF", "KRISTOFF"),
    ("TEEN ANNA", "ANNA"),
    ("TEEN ELSA", "ELSA"),
    ("VICK LENNON", "PHIL"),
    ("VICK", "PHIL"),
    ("INDIANA", "INDY"),
    ("BAILEY", "GEORGE"),
    ("FRO DO", "FRODO"),
    ("YOUNG ELIZABETH", "ELIZABETH"),
    ("DARTH SIDIOUS", "EMPEROR"),
    ("PALPATINE", "EMPEROR"),
    ("PADMÉ", "PADME"),
    ("MACE-WINDU", "MACE WINDU"),
    ("OBI-WAM", "OBI-WAN"),
    ("PAMDE", "PADME"),
    ("THREEPIO", "C-3PO"),
    ("COUNT DOOKU", "DOOKU"),
    ("ODIN ALLFATHER", "ODIN"),
    ("YOUNG CARL", "CARL"),
    ("YOUNG ELLIE", "ELLIE"),
]