# dictionary that converts character IDs into fuly presentable character names
id_to_full_dict = {
    0: 'Jake Sully - Avatar',
    1: 'Loki - The Avengers',
    2: 'Thor - The Avengers',
    3: 'John Bender - The Breakfast Club',
    4: 'Carl Fredricksen - UP',
    5: 'Finn McMissile - Cars 2',
    6: 'Tow Mater - Cars',
    7: 'Lucy Pevensie - Narnia',
    8: 'Lucius Fox - The Dark Knight Rises',
    9: 'Miguel - Coco',
    10: 'Hector - Coco',
    11: 'Batman - The Dark Knight Rises',
    12: 'Gru - Descpicable Me',
    13: 'Lloyd Christmas - Dumb and Dumber',
    14: 'Harry Dunne - Dumb and Dumber',
    15: "Mary Bailey - It's a Wonderful Life",
    16: "Ferris Bueller - Ferris Bueller's Day Off",
    17: 'Marlin - Finding Nemo',
    18: 'Dory - Finding Nemo',
    19: 'Forrest Gump - Forrest Gump',
    20: 'Anna - Frozen',
    21: 'Elsa - Frozen',
    22: 'Kristoff - Frozen',
    23: 'Peter Quill - Guardians of the Galaxy',
    24: 'Phil Wenneck - The Hangover',
    25: 'Stu Price - The Hangover',
    26: 'Alan Garner - The Hangover',
    27: 'Hiccup Haddock - How to Train Your Dragon',
    28: 'Indiana Jones - Indiana Jones Franchise',
    29: 'Willie - Indiana Jones and the Temple of Doom',
    30: "George Bailey - It's A Wonderful life",
    31: 'Samwise Gamgee - Lord of the Rings',
    32: 'Po - Kung Fu Panda',
    33: 'Frodo Baggins - Lord of the Rings',
    34: 'Gandalf - Lord of the Rings',
    35: 'Neo - The Matrix',
    36: 'Captain Jack Sparrow - Pirates of the Caribbean',
    37: 'Shrek - Shrek',
    38: 'Donkey - Shrek',
    39: 'Anakin Skywalker - Star Wars',
    40: 'C-3PO - Star Wars',
    41: 'Luke Skywalker - Star Wars',
    42: 'Han Solo - Star Wars',
    43: 'Leia Organa - Star Wars',
    44: 'Seth - Superbad',
    45: 'Evan - Superbad',
    46: 'Bella Swan - Twilight',
    47: 'Edward Cullen - Twilight',
    48: 'Russell - Up',
    49: 'Dorothy - The Wizard of Oz'}